---
name: tot-la-scoala
on: 
########scheduled events
  schedule: 
    - cron: '*/5 * * * *'
########webhook events
  issues: 
    types: [opened]
########manual events
  repository_dispatch:
    types:
      - manual-trigger-mytest
      - manual-trigger-all
  ### adica workflow can happen in diff-repo , env out of GH 
  workflow_dispatch:
    inputs:
      username: 
        description: Your GitHub username
        required: true
      reason:
        description: Why are you running this workflow manually?
        required: true
        default: I am running tests before implementing an automated workflow
jobs:
  j101:
    runs-on: ubuntu-latest
    steps:
      - name: prezinta-te
        run: echo Eu sunt pic
  j298:
    runs-on: ubuntu-latest
    steps:
      - name: scrie putin
        run: >
          echo "Un client numit [ ${{ github.event.inputs.username }} ] a declansat workflow"
          echo " pt ca/din motivul:  [ ${{ github.event.inputs.reason }} ]"
