---
name: tot-la-scoala
on:
  workflow_dispatch:
    inputs:
      username: null
      description: Your GitHub username
      required: true
    reason:
      description: Why are you running this workflow manually?
      required: true
      default: I am running tests before implementing an automated workflow
jobs:
  j101:
    runs-on: ubuntu-latest
    steps:
      - name: prezinta-te
        run: echo Eu sunt pic
      - name: prezinta-te si tu
        run: echo Eu sunt poc

