---
name: tot-la-scoala
on: 
########scheduled events
  schedule: 
      - cron: '* */8 * * *'
##    - cron: '*/15 * * * *'  la 15 min
########webhook events
  issues: 
    types: [opened]
  issue_comment: 
    types: [created]
########manual events
  repository_dispatch:
    types:
      - manual-trigger-mytest
      - manual-trigger-all
  ### adica workflow can happen in diff-repo , env out of GH 
  workflow_dispatch:
    inputs:
      username: 
        description: Your GitHub username
        required: true
      reason:
        description: Why are you running this workflow manually?
        required: true
        default: I am running tests before implementing an automated workflow
jobs:
  j101:
    runs-on: ubuntu-latest
    steps:
      - name: prezinta-te
        run: echo Eu sunt pic
  j298:
    runs-on: ubuntu-latest
    steps:
      - name: scrie putin
        run: >
          echo "Un client numit [ ${{ github.event.inputs.username }} ] a declansat workflow"
          echo " pt ca/din motivul:  [ ${{ github.event.inputs.reason }} ]"
  j348:
    runs-on: ubuntu-latest
    steps:
      - name: show me the HOME
        run: echo $HOME
      - name: show me the WORKSPACE
        run: echo $GITHUB_WORKSPACE
      - name: show me the WORKFLOW
        run: echo $GITHUB_EVENT_PATH
      - name: show me the x
        run: echo $GITHUB_ACTION_PATH
      - name: show me the data
        run: cat $GITHUB_EVENT_PATH
##
  j492:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - uses: micnncim/action-lgtm-reaction@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        GIPHY_API_KEY: ${{ secrets.TEST_G93 }}
      with:
        trigger: '[".*looks good to me bre.*"]'
        overide: true
        source: 'giphy'


  ###
  j528:
    runs-on: ubuntu-latest
    steps:
    - run: echo "$GITHUB_CONTEXT"
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }}
