name: Pipelineline
run-name: PLLL executed by ${{ github.actor }}
on: workflow_dispatch
jobs:
  zidul101:
    runs-on: ubuntu-latest
    steps:
    - run: echo 1
  zidul203:
    runs-on: ubuntu-latest
    steps:
    - run: echo 2
