name: Pipelineline
run-name: PLLL executed by ${{ github.actor }}
on: workflow_dispatch
jobs:
  zidul101:
    runs-on: ubuntu-latest
    steps:
    - name: zid101
      run: echo 1
    - name: citesc din ctx.github
      run: echo ${{ github.ref }} + ${{ github.event_name }} + ${{ github.repository }}  
    - name: citesc din ctx.job
      run: echo ${{ job.container }} + ${{ job.services }} + ${{job.status}}  
    - name: citesc din ctx.runner
      run: echo ${{ runner.os }} + ${{ runner.name }} + ${{ runner.arch }}  
    - name: expresii-cu-bool
      run: echo ${{ github.ref == 'refs/heads/main' }}   
  zidul203:
    runs-on: ubuntu-latest
    steps:
    - run: echo 2
