name: Pipelineline
run-name: PLLL executed by ${{ github.actor }}
on: workflow_dispatch
env:
  PIPE: cicd-at-wflow-level
jobs:
  zidul101:
    env:
      PIPE: cicd-at-jobs
    runs-on: ubuntu-latest
    steps:
    - name: zid101
      run: |
           echo 1
           echo ${{ env.PIPE }}
    - name: citesc din ctx.github
      run: echo ${{ github.ref }} + ${{ github.event_name }} + ${{ github.repository }}  
    - name: citesc din ctx.job
      run: echo ${{ job.container }} + ${{ job.services }} + ${{job.status}}  
    - name: citesc din ctx.runner
      run: echo ${{ runner.os }} + ${{ runner.name }} + ${{ runner.arch }}  
    - name: expresii-cu-bool
      run: echo ${{ github.ref == 'refs/heads/main' }}   
  zidul203:
    runs-on: ubuntu-latest
    steps:
    - name: sunt pe zidul263
      env:
        PIPE: cicd-at-step
      run: echo 2
    - name: create item with token
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo ${{ env.GITHUB_TOKEN }}
    
